### ISSUE TITLE
Разработать базовую форму вывода информации о преподавателе

### ISSUE THREAD

**Issue by callmemars1** [callmemars1/suai-bot-student-telegram-client#2]
## Требования:
Информация должна выводиться таким образом
- ФИО
- Ученая степень (если есть)
- Институт
- Кафедра
- Должность
- Дополнительно:
  - Телефон
  - Почта
_________________________
Если в секцию "Дополнительно" нечего записать, то она не выводится. Т.к. поиск будет искать ближайшие совпадения с запросом, то вывод может содержать несколько результатов, упорядоченных по степени совпадения.
В таком случае должна быть возможность листать результаты, как это было с расписанием
Структурный пример формы и json ниже:
### Макет

![Image](https://user-images.githubusercontent.com/86615975/166124352-e628cee8-b147-480b-b1bf-ffdebf95dc0b.png)

### Json
```yaml
{
    "university": "SUAI",
    "teachers":
    [
      {
        "name": "Иванов Иван Иванович",
        "academicDegree": "Кандидат физико-математических наук, доцент",
        "position": "Доцент",
        "institute": "Институт чего-то физико-математического хз",
        "department": "Кафедра исследования исследований",
        "phone": "89765432112",
        "email": "ivanov_fizik@suai.ru"
      },
      {
        "name": "Иванков Петр Алексеевич",
        "academicDegree": "Кандидат экономических наук, доцент",
        "position": "Доцент",
        "institute": "Экономический факультет",
        "department": "Кафедра денег",
        "phone": "89999999999",
        "email": "petr.alek$$$evich@suai.ru"
      }
    ]
  }
```
